name: Fetch UK Bank Holidays
on:
  workflow_dispatch:
  schedule:
    - cron: '17 0 1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v6

      - name: Fetch latest data
        run: |
          curl https://www.gov.uk/bank-holidays.json | jq . > _data/holidays.json

      - name: Commit and push if it changed
        run: |
          git diff
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add -A
          git diff --staged --quiet || git commit -m "Chore: Pull latest data for `date +'%Y-%m-%d %H:%M'`"
          git push